site_name: SUMO wiki ja
theme:
  name: 'material'
  language: 'ja'
  logo: 'img/MediaWikiSidebarLogo.png'

extra:
  search:
    language 'ja'

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

nav:
- トップ: 'index.md'
- ドキュメント:
  - 概要: 'user_doc.md'
  - イントロダクション:
    - SUMO早分かり: 'document/sumo_at_a_glance.md'
  - 基本的な使い方:
    - ドキュメントでの記法: 'document/basics_notation.md'
    - 基本的なコンピュータスキル: 'document/basics_basic_computer_skills.md'
    - チュートリアル: 'document/tutrials.md'
    - インストール: 'document/install.md'
    - コマンドラインアプリケーション: 'document/basics_using_the_command_line_applications.md'
  - 理論:
    - 交通シミュレーション理論: 'document/theory_traffic_simulations.md'
- ダウンロード: 'download.md'

extra_css:
  - css/extra.css
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"

google_analytics: ['UA-140953050-1', 'kudzuyu.github.io/SUMO-wiki-ja']