site_name: SUMO wiki ja
site_url: https://kudzuyu.github.io/SUMO-wiki-ja/
theme:
  name: 'material'
  language: 'ja'
  logo: 'img/MediaWikiSidebarLogo.png'


extra:
  search:
    language 'ja'
  AdditionalFile: '[*additional-file*](/docs/SUMO.html#format_of_additional_files)'
  AdditionalFiles: '[*additional-files*](/docs/SUMO.html#format_of_additional_files)'
  DT_2DBoundingBox: '[*&lt;2D-BOUNDING_BOX&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_2DPosition: '[*&lt;2D-POSITION&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_BOOL: '[*&lt;BOOL&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_Color: '[*&lt;COLOR&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_FILE: '[*&lt;FILE&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_FLOAT: '[*&lt;FLOAT&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_IDList: '[*&lt;ID&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_INT: '[*&lt;INT&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_NET: '[*&lt;NETWORK_FILE&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_PATH: '[*&lt;PATH&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_PROJ_DEF: '[*&lt;PROJ_DEFINITION&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_Routes: '[*&lt;ROUTES_FILE&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_STR: '[*&lt;STRING&gt;*](/docs/Basics/Notation.html#データタイプ)'
  DT_TIME: '[*&lt;TIME&gt;*](/docs/Basics/Notation.html#データタイプ)'
  Outdated: '<div style="background: #801010; padding: .5em; border: 1px dashed #ffcc44; margin-right:10px; margin-left:10px; color: #ffffff">This information is outdated.</div>'
  Source: 'https://github.com/eclipse/sumo/blob/master/'
  SUMO: '***&lt;SUMO_HOME&gt;***'
  SUMOUSERConference: '[SUMO User Conference](http://sumo.dlr.de/2020/)'

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

nav:
  - トップ: 'index.md'
  - ドキュメント: 'user_doc.md'
  - ダウンロード: 'download.md'

extra_css:
  - css/extra.css
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"

google_analytics: ['UA-140953050-1', 'kudzuyu.github.io/SUMO-wiki-ja']
