site_name: SUMO wiki ja
theme: material

extra:
  search:
    language 'ja'

markdown_extensions:
  - admonition

nav:
- トップ: 'index.md'
- ドキュメント:
  - インストール: 'document/install.md'
- ダウンロード: 'download.md'