site_name: SUMO wiki ja
site_url: https://kudzuyu.github.io/SUMO-wiki-ja/
theme:
  name: 'material'
  language: 'ja'
  logo: 'img/MediaWikiSidebarLogo.png'

extra:
  search:
    language 'ja'

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

nav:
- トップ: 'index.md'
- ドキュメント:
  - 概要: 'user_doc.md'
  - イントロダクション:
    - SUMO早分かり: 'document/sumo_at_a_glance.md'
  - 基本的な使い方:
    - ドキュメントでの記法: 'document/basics_notation.md'
    - 基本的なコンピュータスキル: 'document/basics_basic_computer_skills.md'
    - チュートリアル: 'document/tutrials.md'
    - インストール: 'document/install.md'
    - コマンドラインアプリケーション: 'document/basics_using_the_command_line_applications.md'
    - アプリへの入力に対するバリデーション: 'document/basics_xmlvalidation.md'
  - ネットワーク構築:
    - 抽象的ネットワーク生成: 'document/networks_abstract_network_generation.md'
    - 標高: 'document/networks_elevation.md'
    - 地理座標系: 'document/geo-coordinates.md'
  - シミュレーション:
    - 基本的な定義: 'document/simulation_basic_definition.md'
    - 交通信号: 'document/simulation_traffic_lights.md'
    - 水路: 'document/simulation_waterways.md'
    - ランダム性: 'document/simulation_randomness.md'
  - 理論:
    - 交通シミュレーション理論: 'document/theory_traffic_simulations.md'
  - アプリケーションマニュアル:
    - SUMO: 'document/SUMO.md'
- ダウンロード: 'download.md'

extra_css:
  - css/extra.css
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"

google_analytics: ['UA-140953050-1', 'kudzuyu.github.io/SUMO-wiki-ja']